development:
  environment: development
  host: localhost
  port: 6379
  db: 6


test:
  environment: test
  host: localhost
  port: 6379
  db: 6

production:
  environment: production
  host: 192.168.2.103
  port: 6379
  db: 6
